//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoBiding.Web.Sys_Users {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtUserNickName;
		protected global::System.Web.UI.WebControls.TextBox txtPassword;
		protected global::System.Web.UI.WebControls.TextBox txtUserName;
		protected global::System.Web.UI.WebControls.TextBox txtDescription;
		protected global::System.Web.UI.WebControls.TextBox txtUserProfile;
		protected global::System.Web.UI.WebControls.TextBox txtGender;
		protected global::System.Web.UI.WebControls.TextBox txtAddress;
		protected global::System.Web.UI.WebControls.TextBox txtContacterName;
		protected global::System.Web.UI.WebControls.TextBox txtTelephonePhone;
		protected global::System.Web.UI.WebControls.TextBox txtTelephonePhone2;
		protected global::System.Web.UI.WebControls.TextBox txtMobilePhone;
		protected global::System.Web.UI.WebControls.TextBox txtMobilePhone2;
		protected global::System.Web.UI.WebControls.TextBox txtEmail;
		protected global::System.Web.UI.WebControls.TextBox txtQQ;
		protected global::System.Web.UI.WebControls.TextBox txtFax;
		protected global::System.Web.UI.WebControls.TextBox txtDistrictId;
		protected global::System.Web.UI.WebControls.TextBox txtOnCreate;
		protected global::System.Web.UI.WebControls.CheckBox chkDeleted;
		protected global::System.Web.UI.WebControls.TextBox txtManufacturerGUID;
		protected global::System.Web.UI.WebControls.TextBox txtPostCode;
		protected global::System.Web.UI.WebControls.TextBox txtWebSite;
		protected global::System.Web.UI.WebControls.TextBox txtNotes;
		protected global::System.Web.UI.WebControls.TextBox txtDisplayOrder;
		protected global::System.Web.UI.WebControls.TextBox txtScores;
		protected global::System.Web.UI.WebControls.TextBox txtLoginIp;
		protected global::System.Web.UI.WebControls.TextBox txtLastLoginTime;
		protected global::System.Web.UI.WebControls.TextBox txtLevelId;
		protected global::System.Web.UI.WebControls.TextBox txtLastLoginIp;
		protected global::System.Web.UI.WebControls.TextBox txtDefaultAddressId;
		protected global::System.Web.UI.WebControls.TextBox txtRecommenderId;
		protected global::System.Web.UI.WebControls.TextBox txtUserLoginType;
		protected global::System.Web.UI.WebControls.TextBox txtOpenId;
		protected global::System.Web.UI.WebControls.TextBox txtAccessToken;
		protected global::System.Web.UI.WebControls.TextBox txtRecommendUserId;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
