//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoBiding.Web.Sys_Users {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblSys_UserId;
	protected global::System.Web.UI.WebControls.Label lblUserNickName;
	protected global::System.Web.UI.WebControls.Label lblUserGUID;
	protected global::System.Web.UI.WebControls.Label lblPassword;
	protected global::System.Web.UI.WebControls.Label lblUserName;
	protected global::System.Web.UI.WebControls.Label lblDescription;
	protected global::System.Web.UI.WebControls.Label lblUserProfile;
	protected global::System.Web.UI.WebControls.Label lblGender;
	protected global::System.Web.UI.WebControls.Label lblAddress;
	protected global::System.Web.UI.WebControls.Label lblContacterName;
	protected global::System.Web.UI.WebControls.Label lblTelephonePhone;
	protected global::System.Web.UI.WebControls.Label lblTelephonePhone2;
	protected global::System.Web.UI.WebControls.Label lblMobilePhone;
	protected global::System.Web.UI.WebControls.Label lblMobilePhone2;
	protected global::System.Web.UI.WebControls.Label lblEmail;
	protected global::System.Web.UI.WebControls.Label lblQQ;
	protected global::System.Web.UI.WebControls.Label lblFax;
	protected global::System.Web.UI.WebControls.Label lblDistrictId;
	protected global::System.Web.UI.WebControls.Label lblOnCreate;
	protected global::System.Web.UI.WebControls.Label lblDeleted;
	protected global::System.Web.UI.WebControls.Label lblManufacturerGUID;
	protected global::System.Web.UI.WebControls.Label lblPostCode;
	protected global::System.Web.UI.WebControls.Label lblWebSite;
	protected global::System.Web.UI.WebControls.Label lblNotes;
	protected global::System.Web.UI.WebControls.Label lblDisplayOrder;
	protected global::System.Web.UI.WebControls.Label lblScores;
	protected global::System.Web.UI.WebControls.Label lblLoginIp;
	protected global::System.Web.UI.WebControls.Label lblLastLoginTime;
	protected global::System.Web.UI.WebControls.Label lblLevelId;
	protected global::System.Web.UI.WebControls.Label lblLastLoginIp;
	protected global::System.Web.UI.WebControls.Label lblDefaultAddressId;
	protected global::System.Web.UI.WebControls.Label lblRecommenderId;
	protected global::System.Web.UI.WebControls.Label lblUserLoginType;
	protected global::System.Web.UI.WebControls.Label lblOpenId;
	protected global::System.Web.UI.WebControls.Label lblAccessToken;
	protected global::System.Web.UI.WebControls.Label lblRecommendUserId;


       
    }
}
