//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoBiding.Web.Sys_UserTrackers {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtTrackerName;
		protected global::System.Web.UI.WebControls.TextBox txtTrackerCityIds;
		protected global::System.Web.UI.WebControls.TextBox txtTrackerIndustryIds;
		protected global::System.Web.UI.WebControls.TextBox txtCreateTime;
		protected global::System.Web.UI.WebControls.TextBox txtKeyword1;
		protected global::System.Web.UI.WebControls.TextBox txtKeyword2;
		protected global::System.Web.UI.WebControls.TextBox txtKeyword3;
		protected global::System.Web.UI.WebControls.TextBox txtKeyword4;
		protected global::System.Web.UI.WebControls.TextBox txtKeyword5;
		protected global::System.Web.UI.WebControls.TextBox txtSys_UserId;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
