//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoBiding.Web.Sys_UserTrackers {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblUserTrackerId;
	protected global::System.Web.UI.WebControls.Label lblTrackerName;
	protected global::System.Web.UI.WebControls.Label lblTrackerCityIds;
	protected global::System.Web.UI.WebControls.Label lblTrackerIndustryIds;
	protected global::System.Web.UI.WebControls.Label lblCreateTime;
	protected global::System.Web.UI.WebControls.Label lblKeyword1;
	protected global::System.Web.UI.WebControls.Label lblKeyword2;
	protected global::System.Web.UI.WebControls.Label lblKeyword3;
	protected global::System.Web.UI.WebControls.Label lblKeyword4;
	protected global::System.Web.UI.WebControls.Label lblKeyword5;
	protected global::System.Web.UI.WebControls.Label lblSys_UserId;


       
    }
}
