//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoBiding.Web.Bids {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblBidId;
		protected global::System.Web.UI.WebControls.TextBox txtBidTitle;
		protected global::System.Web.UI.WebControls.TextBox txtBidPublishTime;
		protected global::System.Web.UI.WebControls.TextBox txtBidContent;
		protected global::System.Web.UI.WebControls.TextBox txtCityId;
		protected global::System.Web.UI.WebControls.TextBox txtProvinceId;
		protected global::System.Web.UI.WebControls.TextBox txtBidNumber;
		protected global::System.Web.UI.WebControls.TextBox txtBidExpireTime;
		protected global::System.Web.UI.WebControls.TextBox txtBidFileName;
		protected global::System.Web.UI.WebControls.TextBox txtBidProjectName;
		protected global::System.Web.UI.WebControls.TextBox txtBidAgent;
		protected global::System.Web.UI.WebControls.TextBox txtBidKeywords;
		protected global::System.Web.UI.WebControls.TextBox txtBidContacter;
		protected global::System.Web.UI.WebControls.TextBox txtBidContacterMobile;
		protected global::System.Web.UI.WebControls.TextBox txtBidContacterTel;
		protected global::System.Web.UI.WebControls.TextBox txtBidContacterAddress;
		protected global::System.Web.UI.WebControls.TextBox txtBidContacterURL;
		protected global::System.Web.UI.WebControls.TextBox txtBidSourceURL;
		protected global::System.Web.UI.WebControls.TextBox txtBidSourceName;
		protected global::System.Web.UI.WebControls.TextBox txtCreateTime;
		protected global::System.Web.UI.WebControls.TextBox txtLastChangeTime;
		protected global::System.Web.UI.WebControls.TextBox txtBidType;
		protected global::System.Web.UI.WebControls.TextBox txtBidFileNameURI;
		protected global::System.Web.UI.WebControls.TextBox txtBidSpiderName;
		protected global::System.Web.UI.WebControls.TextBox txtBidCategoryId;
		protected global::System.Web.UI.WebControls.TextBox txtBidCompanyId;
		protected global::System.Web.UI.WebControls.TextBox txtBidCompanyName;
		protected global::System.Web.UI.WebControls.TextBox txtBidOpenTime;
		protected global::System.Web.UI.WebControls.TextBox txtBidPlatFrom;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
