//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoBiding.Web.Bids {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblBidId;
	protected global::System.Web.UI.WebControls.Label lblBidTitle;
	protected global::System.Web.UI.WebControls.Label lblBidPublishTime;
	protected global::System.Web.UI.WebControls.Label lblBidContent;
	protected global::System.Web.UI.WebControls.Label lblCityId;
	protected global::System.Web.UI.WebControls.Label lblProvinceId;
	protected global::System.Web.UI.WebControls.Label lblBidNumber;
	protected global::System.Web.UI.WebControls.Label lblBidExpireTime;
	protected global::System.Web.UI.WebControls.Label lblBidFileName;
	protected global::System.Web.UI.WebControls.Label lblBidProjectName;
	protected global::System.Web.UI.WebControls.Label lblBidAgent;
	protected global::System.Web.UI.WebControls.Label lblBidKeywords;
	protected global::System.Web.UI.WebControls.Label lblBidContacter;
	protected global::System.Web.UI.WebControls.Label lblBidContacterMobile;
	protected global::System.Web.UI.WebControls.Label lblBidContacterTel;
	protected global::System.Web.UI.WebControls.Label lblBidContacterAddress;
	protected global::System.Web.UI.WebControls.Label lblBidContacterURL;
	protected global::System.Web.UI.WebControls.Label lblBidSourceURL;
	protected global::System.Web.UI.WebControls.Label lblBidSourceName;
	protected global::System.Web.UI.WebControls.Label lblCreateTime;
	protected global::System.Web.UI.WebControls.Label lblLastChangeTime;
	protected global::System.Web.UI.WebControls.Label lblBidType;
	protected global::System.Web.UI.WebControls.Label lblBidFileNameURI;
	protected global::System.Web.UI.WebControls.Label lblBidSpiderName;
	protected global::System.Web.UI.WebControls.Label lblBidCategoryId;
	protected global::System.Web.UI.WebControls.Label lblBidCompanyId;
	protected global::System.Web.UI.WebControls.Label lblBidCompanyName;
	protected global::System.Web.UI.WebControls.Label lblBidOpenTime;
	protected global::System.Web.UI.WebControls.Label lblBidPlatFrom;


       
    }
}
