//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoBiding.Web.Citys {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtCityID;
		protected global::System.Web.UI.WebControls.TextBox txtCityName;
		protected global::System.Web.UI.WebControls.TextBox txtZipCode;
		protected global::System.Web.UI.WebControls.TextBox txtProvinceID;
		protected global::System.Web.UI.WebControls.TextBox txtDateCreated;
		protected global::System.Web.UI.WebControls.TextBox txtDateUpdated;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
