//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mercury.Web.Citys {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblCityID;
	protected global::System.Web.UI.WebControls.Label lblCityName;
	protected global::System.Web.UI.WebControls.Label lblZipCode;
	protected global::System.Web.UI.WebControls.Label lblProvinceID;
	protected global::System.Web.UI.WebControls.Label lblDateCreated;
	protected global::System.Web.UI.WebControls.Label lblDateUpdated;


       
    }
}
