//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoBiding.Web.Spiders {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtSpiderName;
		protected global::System.Web.UI.WebControls.TextBox txtSpiderUrl;
		protected global::System.Web.UI.WebControls.TextBox txtCreateTime;
		protected global::System.Web.UI.WebControls.TextBox txtEncodeType;
		protected global::System.Web.UI.WebControls.TextBox txtListExpression;
		protected global::System.Web.UI.WebControls.TextBox txtDetailExpression;
		protected global::System.Web.UI.WebControls.TextBox txtSpiderUrlPrefix;
		protected global::System.Web.UI.WebControls.TextBox txtDistrictId;
		protected global::System.Web.UI.WebControls.TextBox txtCityId;
		protected global::System.Web.UI.WebControls.TextBox txtProvinceId;
		protected global::System.Web.UI.WebControls.TextBox txtTitleExpression;
		protected global::System.Web.UI.WebControls.TextBox txtPublishExpression;
		protected global::System.Web.UI.WebControls.TextBox txtContentExpression;
		protected global::System.Web.UI.WebControls.TextBox txtSourceExpression;
		protected global::System.Web.UI.WebControls.TextBox txtFilenameExpressoin;
		protected global::System.Web.UI.WebControls.TextBox txtBidType;
		protected global::System.Web.UI.WebControls.TextBox txtStatus;
		protected global::System.Web.UI.WebControls.TextBox txtHttpMethod;
		protected global::System.Web.UI.WebControls.TextBox txtPageParameter;
		protected global::System.Web.UI.WebControls.CheckBox chkIsActive;
		protected global::System.Web.UI.WebControls.TextBox txtSpiderType;
		protected global::System.Web.UI.WebControls.TextBox txtPageCount;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
