//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoBiding.Web.Spiders {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblSpiderId;
	protected global::System.Web.UI.WebControls.Label lblSpiderName;
	protected global::System.Web.UI.WebControls.Label lblSpiderUrl;
	protected global::System.Web.UI.WebControls.Label lblCreateTime;
	protected global::System.Web.UI.WebControls.Label lblEncodeType;
	protected global::System.Web.UI.WebControls.Label lblListExpression;
	protected global::System.Web.UI.WebControls.Label lblDetailExpression;
	protected global::System.Web.UI.WebControls.Label lblSpiderUrlPrefix;
	protected global::System.Web.UI.WebControls.Label lblDistrictId;
	protected global::System.Web.UI.WebControls.Label lblCityId;
	protected global::System.Web.UI.WebControls.Label lblProvinceId;
	protected global::System.Web.UI.WebControls.Label lblTitleExpression;
	protected global::System.Web.UI.WebControls.Label lblPublishExpression;
	protected global::System.Web.UI.WebControls.Label lblContentExpression;
	protected global::System.Web.UI.WebControls.Label lblSourceExpression;
	protected global::System.Web.UI.WebControls.Label lblFilenameExpressoin;
	protected global::System.Web.UI.WebControls.Label lblBidType;
	protected global::System.Web.UI.WebControls.Label lblStatus;
	protected global::System.Web.UI.WebControls.Label lblHttpMethod;
	protected global::System.Web.UI.WebControls.Label lblPageParameter;
	protected global::System.Web.UI.WebControls.Label lblIsActive;
	protected global::System.Web.UI.WebControls.Label lblSpiderType;
	protected global::System.Web.UI.WebControls.Label lblPageCount;


       
    }
}
